### ISSUE TITLE
Update brothers section of website

### ISSUE THREAD

**Issue by mysticuno** [Dsan10s/NDWebsite#12]
Alas, our beloved 2015's have graduated and we must adjust our brothers section as such. We should save the info on the 2015's, shift everyone over, and make a template page for the 2019's.

#1919's

**Comment by mysticuno** [comment]
@Dsan10s closed?

**Comment by Dsan10s** [comment]
Oh whoops, never noticed this, yea I already did it

**Comment by mysticuno** [comment]
Closed as of 990d82d0552bb36c5e138839809fc3935e0aad74
